CREATE TABLE Partners(
ID_partners INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Type_partner NVARCHAR(10) NOT NULL,
Name_partner NVARCHAR(100) NOT NULL,
Director NVARCHAR(100) NOT NULL,
Email NVARCHAR(50),
Phone_number NVARCHAR(13) NOT NULL,
Partners_address NVARCHAR(250) NOT NULL,
INN NVARCHAR(15) UNIQUE NOT NULL,
Raiting SMALLINT NOT NULL
)